### ISSUE TITLE
Error in Applying Migrations

### ISSUE THREAD

**Issue by Jinansh230705** [Rupesh180902/LinkScrapper#1]
After cloning and Navigating to the project directory
the 3rd step gives error 
`C:\Users\Admin\Desktop\LinkScrapper>python manage.py migrate
python: can't open file 'C:\\Users\\Admin\\Desktop\\LinkScrapper\\manage.py': [Errno 2] No such file or directory`

**Comment by RupeshDev18** [comment]
have you installed django?

**Comment by RupeshDev18** [comment]
or check with dir or ls depending on Operating system that manage.py file is present or not if not then navigate one folder deeper

**Comment by Jinansh230705** [comment]
> or check with dir or ls depending on Operating system that manage.py file is present or not if not then navigate one folder deeper

Oh ok,
thank you for your help
